server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  cloud:
    consul:
      discovery:
        healthCheckPath: /actuator/health
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2

management:
  security:
    enabled: false
